version: '3'
services:
  app:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on: 
      - redis
      
  redis:
    restart: always
    image: redis:latest
    ports:
      - '6379:6379'

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
